### ISSUE TITLE
Add training instructions

### ISSUE THREAD

**Issue by ntietz** [ntietz/tweetment#1]
The pre-trained model is nice, but someone might want to train their own, so instructions for that should be added.

I probably will get to this after my finals, over winter break.

**Comment by antmaiorino** [comment]
Thanks for providing the training instructions!
Unfortunately I couldn't run it because it looks like there's a missing script. I'm talking about the script under "../cache/twokenizer/twokenize.sh", which is called from the "prep_input.sh" script.

**Comment by ntietz** [comment]
That script is supposed to be downloaded when you run the `download.sh` script. Could you run that again and see if there are any errors? Also, could you list the contents of the cache directory so I can see what did and did not get downloaded for you?
