### ISSUE TITLE
Ignore empty lines in tweets.txt

### ISSUE THREAD

**Issue by ijkilchenko** [ntietz/tweetment#2]
Whatever the input file, say tweets.txt, the script shouldn't try to find words in empty lines and possibly break. This is an issue.

**Comment by ntietz** [comment]
Confirmed, the script breaks on empty lines. I'll issue a fix shortly.

**Comment by ntietz** [comment]
It now withstands blank lines anywhere in the input file, issuing a warning. The warning is appropriate since otherwise, the output can be expected to align with the input via line numbers.
